profile: local

spring:
  application:
    name: sample-springboot-kotlin
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:sample-db-springboot-kotlin;MODE=MYSQL;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1
    username: sa
    password:
    hikari:
      minimum-idle: 5                      # 최소 유지할 커넥션 수
      maximum-pool-size: 10                # 최대 커넥션 수
      idle-timeout: 600000                 # 커넥션이 사용되지 않을 경우 대기 시간 (밀리초)
      max-lifetime: 1800000                # 커넥션의 최대 수명 (밀리초)
      connection-timeout: 30000            # 커넥션 풀에서 커넥션을 얻기까지의 최대 대기 시간 (밀리초)
      pool-name: HikariCP                  # 커넥션 풀의 이름
      connection-test-query: SELECT 1      # 커넥션을 확인할 때 사용할 쿼리 (MySQL 기준)
  sql:
    # DB초기화(schema.sql, data.sql) , [always : 기동 시 매번 동작, never : 기동 시 동작하지 않음]
    init:
      schema-locations: classpath*:initdata/${profile}/schema.sql, classpath*:initdata/${profile}/schema.sql
      data-locations: classpath*:initdata/${profile}/data.sql
      mode: always
  jpa:
    #jpa 사용 환경에서 data.sql을 정상적으로 동작하게 하는 옵션
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    show-sql: true
    format-sql: true


